### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by gwenxia** [zhuyuqing/bestconf#1]
[root@vmaxdap bestconf-master]# pwd
/home/performance/bestconf-master
[root@vmaxdap bestconf-master]# ll
total 40
drwxr-xr-x 4 root root 4096 Feb 15  2017 bestconfs
drwxr-xr-x 4 root root 4096 Nov  8 10:12 data
drwxr-xr-x 6 root root 4096 Feb 15  2017 deploy
-rw-r--r-- 1 root root 2975 Feb 15  2017 hadoop.md
drwxr-xr-x 2 root root 4096 Feb 15  2017 lib
drwxr-xr-x 2 root root 4096 Feb 15  2017 pics
-rw-r--r-- 1 root root 1821 Feb 15  2017 README.md
drwxr-xr-x 6 root root 4096 Feb 15  2017 scripts
-rw-r--r-- 1 root root 2712 Feb 15  2017 spark.md
drwxr-xr-x 8 root root 4096 Feb 15  2017 src
[root@vmaxdap bestconf-master]# sh ./deploy/bin/start.sh 
/usr/java/jdk
java.lang.ClassNotFoundException: cn.ict.zyq.bestConf.cluster.InterfaceImpl.TomcatConfigReadin
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
	at cn.ict.zyq.bestConf.cluster.Main.AutoTestAdjust.<init>(AutoTestAdjust.java:83)
	at cn.ict.zyq.bestConf.bestConf.BestConf.<init>(BestConf.java:83)
	at cn.ict.zyq.bestConf.bestConf.BestConf.startOneTest(BestConf.java:297)
	at cn.ict.zyq.bestConf.bestConf.BestConf.main(BestConf.java:293)

Header of dataset:

@relation InitialSetByLHS

@attribute executorTerminationTimeoutMillis numeric
@attribute maxConnections numeric
@attribute maxKeepAliveRequests numeric
@attribute connectionTimeout numeric
@attribute acceptorThreadCount numeric
@attribute minSpareThreads numeric
@attribute asyncTimeout numeric
@attribute socketBuffer numeric
@attribute maxThreads numeric
@attribute acceptCount numeric
@attribute processorCache numeric
@attribute keepAliveTimeout numeric

@data

Total number of collected performances is : 0
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)

**Comment by zhuyuqing** [comment]
"java.lang.ClassNotFoundException: cn.ict.zyq.bestConf.cluster.InterfaceImpl.TomcatConfigReadin"
You are not having the class codes "TomcatConfigReadin" in your sources

Please follow the steps on https://github.com/zhuyuqing/bestconf/blob/master/doc/QuickStart.md
